import { CONFIG, DICT } from './config.js';
import { state, dom, $, toast, updateUI, updateButtonStates, mouse, setMouseForce } from './state.js';
import { camera } from './scene.js';

let handLandmarker=null, webcamRunning=false, lastVideoTime=-1, gestureCooldown=0, indexHistory=[], isPinching=false, pinchStartTime=0, lastTwoHandDist=-1, lastDetectTime=0;
let lastX=0,lastY=0;
const ctx=dom.handCanvas.getContext('2d');
const CONNECTIONS=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[0,17],[17,18],[18,19],[19,20]];

export function processHands(t,dt,nextModel,setViewMode){if(!webcamRunning||!handLandmarker||state.isPaused)return;const now=performance.now();if(now-lastDetectTime<1000/CONFIG.GESTURE_FPS||dom.video.currentTime===lastVideoTime)return;lastDetectTime=now;lastVideoTime=dom.video.currentTime;let results;try{results=handLandmarker.detectForVideo(dom.video,now);}catch(error){toast(`${DICT[state.lang].loading_err}: ${error.message}`,'error');return;}if(!results.landmarks?.length){setMouseForce(0);state.isDragging=false;isPinching=false;lastTwoHandDist=-1;ctx.clearRect(0,0,dom.handCanvas.width,dom.handCanvas.height);return;}const hand=results.landmarks[0],tip=hand[8],thumb=hand[4],nx=1-tip.x,ny=tip.y;mouse.set(nx*2-1,-(ny*2-1));setMouseForce(1);const pinching=Math.hypot(thumb.x-tip.x,thumb.y-tip.y)<.06;drawHands(results.landmarks,pinching);indexHistory.push({x:nx,y:ny,time:t});indexHistory=indexHistory.filter(p=>t-p.time<.4);if(gestureCooldown>0)gestureCooldown-=dt;else if(indexHistory.length>5&&!pinching){const old=indexHistory[0],cur=indexHistory[indexHistory.length-1],elapsed=cur.time-old.time,dx=cur.x-old.x,dy=cur.y-old.y;if(elapsed>.1&&elapsed<.4){if(Math.abs(dx)/elapsed>1.2&&Math.abs(dx)>.18){nextModel();gestureCooldown=1;indexHistory=[];}else if(Math.abs(dy)/elapsed>1.2&&Math.abs(dy)>.18){setViewMode();gestureCooldown=1;indexHistory=[];}}}if(pinching&&!isPinching){isPinching=true;state.isDragging=true;state.hasDragged=false;lastX=nx*innerWidth;lastY=ny*innerHeight;pinchStartTime=t;}else if(pinching&&isPinching){state.hasDragged=true;const x=nx*innerWidth,y=ny*innerHeight;state.userRotY+=(x-lastX)*.006;state.userRotX=Math.max(-.8,Math.min(.8,state.userRotX+(y-lastY)*.006));lastX=x;lastY=y;}else if(!pinching&&isPinching){isPinching=false;state.isDragging=false;if(!state.hasDragged&&t-pinchStartTime<.3)state.explosion=1;}if(results.landmarks.length>1){const other=results.landmarks[1],dist=Math.hypot(hand[0].x-other[0].x,hand[0].y-other[0].y);if(lastTwoHandDist>0)camera.position.z=Math.max(CONFIG.CAMERA.minZ,Math.min(CONFIG.CAMERA.maxZ,camera.position.z-(dist-lastTwoHandDist)*18));lastTwoHandDist=dist;}else lastTwoHandDist=-1;}
function drawHands(hands,pinching){if(dom.handCanvas.width!==dom.handCanvas.clientWidth)dom.handCanvas.width=dom.handCanvas.clientWidth;if(dom.handCanvas.height!==dom.handCanvas.clientHeight)dom.handCanvas.height=dom.handCanvas.clientHeight;ctx.clearRect(0,0,dom.handCanvas.width,dom.handCanvas.height);for(const hand of hands){ctx.strokeStyle=pinching?'rgba(255,50,50,.8)':'rgba(216,181,106,.8)';ctx.lineWidth=2.5;for(const [a,b] of CONNECTIONS){ctx.beginPath();ctx.moveTo(hand[a].x*dom.handCanvas.width,hand[a].y*dom.handCanvas.height);ctx.lineTo(hand[b].x*dom.handCanvas.width,hand[b].y*dom.handCanvas.height);ctx.stroke();}ctx.fillStyle='#fff';for(const point of hand){ctx.beginPath();ctx.arc(point.x*dom.handCanvas.width,point.y*dom.handCanvas.height,3,0,Math.PI*2);ctx.fill();}}}

export async function toggleGesture(){const button=$('btn-input');if(state.inputMode==='mouse'){state.isAILoading=true;updateUI();button.disabled=true;try{if(!handLandmarker){const vision=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.3/vision_bundle.mjs');const resolver=await vision.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.3/wasm');handLandmarker=await vision.HandLandmarker.createFromOptions(resolver,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task',delegate:'GPU'},runningMode:'VIDEO',numHands:2});}if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera API unavailable');const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}}});dom.video.srcObject=stream;dom.video.onloadeddata=()=>{webcamRunning=true;dom.camContainer.style.display='block';};state.inputMode='gesture';}catch(error){toast(`${DICT[state.lang].loading_err}: ${error.message}`,'error');state.inputMode='mouse';if(dom.video.srcObject)dom.video.srcObject.getTracks().forEach(track=>track.stop());}finally{state.isAILoading=false;button.disabled=false;updateUI();updateButtonStates();}}else{state.inputMode='mouse';webcamRunning=false;dom.camContainer.style.display='none';if(dom.video.srcObject)dom.video.srcObject.getTracks().forEach(track=>track.stop());dom.video.srcObject=null;ctx.clearRect(0,0,dom.handCanvas.width,dom.handCanvas.height);updateUI();updateButtonStates();}}

export function stopGesture(){webcamRunning=false;if(dom.video.srcObject)dom.video.srcObject.getTracks().forEach(track=>track.stop());dom.video.srcObject=null;}
